name: CI

on:
  push:
    branches:
      - initial-documentation

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Build
        uses: docker://ddidier/sphinx-doc:2.2.1-1
        with:
          args: make html
      -
        name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
